# cloudbuild-frontend.yaml
steps:
# Build the frontend Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/vaultwares/frontend-service/frontend-service:${_TAG}', '-f', 'cfg/frontend/Dockerfile', '.']

# Push the frontend Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REGION}-docker.pkg.dev/vaultwares/frontend-service/frontend-service:${_TAG}']

# Deploy the frontend image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'frontend-service'  # Your frontend Cloud Run service name
  - '--image'
  - '${_REGION}-docker.pkg.dev/vaultwares/frontend-service/frontend-service:${_TAG}'
  - '--region=${_REGION}'
  - '--platform=managed'
  - '--allow-unauthenticated' # Adjust authentication as needed, often public for frontends

images:
- '${_REGION}-docker.pkg.dev/vaultwares/frontend-service/frontend-service:${_TAG}'

substitutions:
  _REGION: us-central1
  _TAG: '$COMMIT_SHA' # You can use $COMMIT_SHA here for unique versions
